### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by USERUSERU** [MicrosoftEdge/JSBrowser#46] opened 2017-01-15 14:09 UTC
Could you change code of this program, because number of color is not good for christians. Lets change this number to 677. (There is not very much difference between 6...6 and 677). http://www.color-hex.com/color/667777
Now, I will show fragments, where is this code is use
}
#urlInput:focus {
border-color: #0078D7;
color: #666;

.effect-moveleft .outer-nav a {
color: #666;
padding: 15px;
margin: 0;
cursor: pointer;

#favMenu .url {
font-size: 12px;
color: #666;

**Comment by molant** [comment] 2017-01-15 18:20
Duplicate of #45

**Closed by molant** 2017-01-15 18:20 UTC
